version: "3.9"

services:
  db:
    image: mongo:latest
    restart: always
    volumes:
      - C:\mongodb\data\db:/data/db
    ports:
      - 27017:27017

  backend:
    restart: always
    build: ./backend
    image: libra-alchemy/backend:0.0.1
    ports:
      - 5000:5000

  frontend:
    restart: always
    build: ./frontend/
    image: libra-alchemy/frontend:0.0.1
    ports:
      - 8080:80
    environment:
      - API_SERVER='http://libra_alchemy-backend-1:5000'

networks:
  default:
    name: alchemy

volumes:
  data:
    external: true