version: "3.9"

services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - C:\mongodb\data\db:/data/db
    ports:
      - 27017:27017

  backend:
    restart: always
    build: ./backend
    image: libra-alchemy/backend:0.0.1
    environment:
      - CONFIG_FILE=/opt/config.json
    volumes:
      - ./docker-config.json:/opt/config.json
    ports:
      - 5000:5000

  frontend:
    restart: always
    build: ./frontend/
    image: libra-alchemy/frontend:0.0.1
    ports:
      - 8080:80
    environment:
      - API_SERVER='http://backend:5000'

networks:
  default:
    name: alchemy