apiVersion: v1
kind: Service
metadata: {{ $fullname := printf "%s-%s-frontend" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{- with .Values.frontend }}
spec:
  type: {{ .service.type }}
  {{- if .service.loadBalancerIP }}
  loadBalancerIP: {{ .service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ $fullname }}

{{- end }}