global:
  image:
    pullSecrets: 'reg-cred'

backend:
  replicas: 2
  image:
    pullPolicy: Always
    tag: master
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  config:
    mongo: 
      host: cluster0.fmnymnk.mongodb.net
      db: libra9
      clustered: true
  service:
    type: LoadBalancer
    loadBalancerIP: 34.77.106.78

frontend:
  replicas: 2
  backendAddr: "http://libra-alchemy-libra-alchemy-backend.libra-alchemy.svc"
  image:
    tag: master  
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  service:
    type: LoadBalancer
    loadBalancerIP: 34.76.95.73