apiVersion: apps/v1
kind: Deployment
metadata: {{ $fullname := printf "%s-%s-backend" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
{{- with .Values.backend }}
  selector:
    matchLabels:
      app: {{ $fullname }}
  replicas: {{ default 1 .replicas | int }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      containers:
      {{- with .image }}
      - name: backend
        image: "{{ .repository }}:{{ .tag | default $.Chart.AppVersion }}"
        imagePullPolicy: {{ .pullPolicy }}
      {{- end }}
        env:
          - name: "MONGO_USERNAME"
            valueFrom:
              secretKeyRef:
                name: "{{ .config.mongo.credentialsSecret }}"
                key: username
          - name: "MONGO_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: "{{ .config.mongo.credentialsSecret }}"
                key: password
          - name: "CONFIG_FILE"
            value: "/etc/libralchemy/config.json"

        volumeMounts:
          - name: config
            mountPath: /etc/libralchemy
        ports:
          - containerPort: {{ .service.port | int }}
        readinessProbe:
          httpGet:
            path: /technics
            port: {{ .service.port | int }}
        resources:
{{ toYaml .resources | indent 10 }}
      {{- if $.Values.global.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ $.Values.global.image.pullSecrets }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ $fullname }}
{{- end }}