name: Deploy Alchemy System

on: workflow_dispatch


jobs:
  build-frontend:
    runs-on: ubuntu-latest
 
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Alchemy system has been deleted.'